
spring:
  application:
    name: mentoring-service
  messages:
    basename: messages, errors
  datasource:
    url: jdbc:mysql://localhost:3306/devlink-database
    username: devlink-user
    password: devlink-user
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
      use_sql_comments: true
      format_sql: true
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true


data:
  naverapi:
    clientId:
    clientSecret:
    stt:
      url: https://naveropenapi.apigw.ntruss.com/recog/v1/stt?lang=Kor
      contentType: application/octet-stream
      fileUrl: /Users/kangmingu/Desktop/Goorm_Project/mentoring-service/RecordFile.mp3
    summary:
      url: https://naveropenapi.apigw.ntruss.com/text-summary/v1/summarize
      contentType: application/json




